### ISSUE TITLE
Can't find PlexDL

### ISSUE THREAD

**Issue by KeyFac** [Brhsoftco/GitHubUpdater#2]
I can't find PlexDL modules...
using .net framework 4.7.2 . Did I use a wrong version?

**Comment by Brhsoftco** [comment]
Hello, GitHubUpdater is based off of the same implementation as PlexDL; thanks for reminding me to separate this project :) you can actually download the PlexDL binaries from my repo and use the DLL from there which will allow you to use GitHubUpdater

**Comment by KeyFac** [comment]
OK thanks a lot
